### ISSUE TITLE
Error while installing usd_from_gltf : [USD\include\pxr/base/tf/diagnosticHelper.h(35,10): fatal error C1083: Cannot open include file: 'boost/any.hpp': No such file or directory ]

### ISSUE THREAD

**Issue by 53nthamizh** [google/usd_from_gltf#54]
Hi, 
I've been trying to identify this issue. Couldn't get anything on it. Any idea on this?

gltf.vcxproj -> C:\USDGLTF\build\usd_from_gltf\gltf\Release\gltf.lib
  config.cc
C:\USD\include\pxr/base/tf/diagnosticHelper.h(35,10): fatal error C1083: Cannot open include file: 'boost/any.hpp': No such file or directory [C:\USDGLTF\build\usd_from_gltf\common\common.vcxproj]
  logging.cc
C:\USD\include\pxr/base/tf/diagnosticHelper.h(35,10): fatal error C1083: Cannot open include file: 'boost/any.hpp': No such file or directory [C:\USDGLTF\build\usd_from_gltf\common\common.vcxproj]

![image](https://user-images.githubusercontent.com/8809538/81053388-9f06d680-8ee2-11ea-92d3-6c2a52aac8dd.png)

The log file.
[log.txt](https://github.com/google/usd_from_gltf/files/4579988/log.txt)

**Comment by 53nthamizh** [comment]
[UPDATE] The latest version of USD v20.05 uses Boost 1.70. But Installing boost 1.61 and 1.65.1 in Additional Include directory i.e "USD\include\" fixed the issue. but now I get other issues. 

![image](https://user-images.githubusercontent.com/8809538/81139225-9fef4500-8f82-11ea-8c74-548ad5c56907.png)

**Comment by tharindukprooftec** [comment]
> [UPDATE] The latest version of USD v20.05 uses Boost 1.70. But Installing boost 1.61 and 1.65.1 in Additional Include directory i.e "USD\include" fixed the issue. but now I get other issues.
> 
> ![image](https://user-images.githubusercontent.com/8809538/81139225-9fef4500-8f82-11ea-8c74-548ad5c56907.png)

I got the same issue. how did you fix it?

**Comment by goout** [comment]
@53nthamizh why you closed it ? got the same error:
![image](https://user-images.githubusercontent.com/2082785/84181668-ec520700-aa91-11ea-86c0-caead30327ed.png)

solved with change boost folder path. :)
but

![image](https://user-images.githubusercontent.com/2082785/84183181-26240d00-aa94-11ea-9810-fea676441a0e.png)

**Comment by v-prgmr** [comment]
Any update? I have the same error with any.hpp

**Comment by muhammettaskale** [comment]
I am dealing with the same problem, I could not find the solution

**Comment by mura94** [comment]
Still seeing this issue

**Comment by ghost** [comment]
I am also still getting this issue as well. I can change the boost version in the CmakeList.txt file, however I also get the error: `UFG_SRC\process\..\process/mesh.h(56,25): error C2976: 'std::map': too few template arguments [C:\UFG\build\UFG_SRC\process\process.vcxproj]`

**Comment by rui-fernandes-tfs** [comment]
Still getting the same issue regarding boost/any.hpp

**Comment by ghost** [comment]
I ended up compiling USD 19.05 and then it worked!

**Comment by gonzalo-piffaretti-tfs** [comment]
@braedenf did you build it with VS2017 or were you able to use VS2019??

**Comment by ghost** [comment]
I tried so many things haha. I think I used VS2017 Native x64 and Python 2.7 (making sure other Python version were not in my path) [This](https://www.manicmachinegames.com/blog/2019/1/10/tutorial-setting-up-and-building-pixars-usd-on-windows) guide helped me a lot.
